name: xpu

on:
  push:
    branches:
      - mengfeil/xpu-nightly
    # tags:
    #   - ciflow/xpu/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}
  cancel-in-progress: true

jobs:
  linux-jammy-xpu-py3_8-build:
    name: linux-jammy-xpu-py3.8
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: linux-jammy-xpu-py3.8
      docker-image-name: pytorch-linux-jammy-xpu-2024.0-py3
      runner: linux.idc.xpu.tmp
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 1, runner: "linux.idc.xpu.tmp" },
        ]}

  linux-jammy-xpu-py3_8-test:
    name: linux-jammy-xpu-py3.8
    uses: ./.github/workflows/_xpu-test.yml
    needs: linux-jammy-xpu-py3_8-build
    permissions:
      id-token: write
      contents: read
    with:
      build-environment: linux-jammy-xpu-py3.8
      docker-image: ${{ needs.linux-jammy-xpu-py3_8-build.outputs.docker-image }}
      test-matrix: ${{ needs.linux-jammy-xpu-py3_8-build.outputs.test-matrix }}

  Tests-Failure-And-Report:
    runs-on: linux.idc.xpu.tmp
    permissions:
      issues: write
    env:
      GH_TOKEN: ${{ github.token }}
    needs: linux-jammy-xpu-py3_8-build
    if: always()
    steps:
      - name: Report github issue for XPU nightly
        if: ${{ needs.linux-jammy-xpu-py3_8-build.result == 'success' }}
        run: |
          build_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          repo="${{ github.repository }}"
          gh --repo $repo issue comment 7  \
              --body "XPU Nightly Successful $(date +'%F'), See: $build_url"
      - name: Report github issue when failure detected
        if: ${{ needs.linux-jammy-xpu-py3_8-build.result == 'failure' }}
        run: |
          build_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          notification_list="${{ secrets.ISSUE_NOTIFICATION_LIST }}"
          repo="${{ github.repository }}"
          gh --repo $repo issue comment 7  \
              --body "XPU Nightly Failed $(date +'%F'), See: $build_url
                      cc $notification_list"
